apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
  namespace: ${NAMESPACE}
  labels:
    app: ratelimit
data:
  config.yaml: |
    domain: nginx-ratelimit
    descriptors:
      - key: generic_key
        value: nginx-ratelimit
        rate_limit:
          unit: minute
          requests_per_unit: 5
