[project]
name = "istio-usecases"
version = "0.1.0"
description = "Istio examples and tools"
readme = "readme.md"
authors = [
    { name = "wlanboy", email = "wlanboy@github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
istio-usecases = "istio_usecases:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
