[project]
name = "istio-usecases"
version = "0.1.0"
description = "Istio examples and tools"
readme = "readme.md"
authors = [
    { name = "wlanboy", email = "wlanboy@github.com" }
]
requires-python = ">=3.14"
dependencies = []

[tool.uv]
package = false

[dependency-groups]
dev = [
    "pyright>=1.1.414",
]
